### ISSUE TITLE
Routes match more than advertised

### ISSUE THREAD

**Issue by raquo** [sparsetech/trail#37]
```scala
Root.parse("/hello/world").isDefined   // true
(Root / "hello").parse("/hello/world").isDefined   // true
```

Having read the documentation, I would expect both of those to be `false`, not `true`. I don't see this behaviour explicitly tested (except indirectly [here](https://github.com/sparsetech/trail/blob/master/shared/src/test/scala/trail/RouteParseTests.scala#L23)) so I'm not sure if this is intended or not.

I don't think this is desirable behaviour:
* It makes it impossible to handle 404s – `/hello/world` is not a URL I want _any_ route to match at all
* It requires seemingly non-conflicting routes to be evaluated in a certain order – `Root / "hello"` has to go before `Root`

The only possible workaround is to append `/ ""` to the route, but that only works for `Root / ""`. In other cases it appends an undesirable "/" to the route URL, i.e. `(Root / "hello" / "").url(())` is "/hello/" instead of the desired "/hello".

I think routes should perform an exact match instead of current `startsWith`-like behaviour, and the current behaviour should be opt-in for each route using `Root / "hello" / Rest` or something like that.

---

Also unrelatedly, it appears that the linked gitter room no longer exists.

**Comment by raquo** [comment]
I've [added](https://github.com/raquo/trail/commit/c05790eb40136306a2094fb1d0485485056e6c8a) `Root / "hello" / EndPath` syntax on my fork as a backstop but that's not a good solution really, should be the other way imo, with `/ Rest` opt-in.

**Comment by tindzk** [comment]
Thanks for bringing the issue up. As part of a larger refactoring, I changed this behaviour [in v0.2.0](https://github.com/sparsetech/trail/releases/tag/v0.2.0) (see "Parsing precedence"), but have failed to explain it in the documentation. In my routing tables, I generally sort the routes by length, but occasionally did hit the same problem as you have.

I agree that we should make prefix matches opt-in and introduce `Rest` for this. Since you already have a partial fix, would you mind submitting a pull request that makes these changes?

Edit: I got in touch with Gitter and hope they can resolve the issue with the channel (and others) being inaccessible.
